"""add todo priority and reminders

Revision ID: 3ad97c947a94
Revises: 3be13befa107
Create Date: 2026-06-25 19:30:44.586498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3ad97c947a94'
down_revision: Union[str, None] = '3be13befa107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False))
    op.add_column('todos', sa.Column('reminder_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'reminder_at')
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
