"""add_session_id_to_documents

Revision ID: 51654f5618e5
Revises: 0003_add_chat_session_summary
Create Date: 2026-06-16 17:58:36.147801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '51654f5618e5'
down_revision: Union[str, None] = '47109d712326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'session_id')
    # ### end Alembic commands ###
