"""add sources to chat messages

Revision ID: 6531a72e40ab
Revises: 53c5adc10cfa
Create Date: 2026-06-27 12:05:25.091160
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6531a72e40ab'
down_revision: Union[str, None] = '53c5adc10cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('sources', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'sources')
    # ### end Alembic commands ###
